# Generated by Django 4.2.5 on 2023-12-12 16:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisoft', '0002_alter_calificacion_fecha_alter_comentario_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
