# Generated by Django 4.2.5 on 2023-12-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisoft', '0004_alter_publicacion_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='likes',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='url_imagen',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, default='', max_length=22, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='informacion',
            field=models.CharField(blank=True, default='', max_length=250, null=True),
        ),
    ]
