# Generated by Django 4.2.5 on 2023-12-27 01:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutrisoft', '0007_alter_usuario_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='PublicacionGuardada',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='calificacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='publicaciones',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='nutriologo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones_usuarioCalificado', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='usuario',
            name='url_FotoPerfil',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='publicacion',
            name='url_imagen',
            field=models.CharField(blank=True, default='', max_length=500, null=True),
        ),
    ]
